In [1]:
# !pip install pandas xlrd
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Get data

Data from [data.gov](https://catalog.data.gov/dataset/federal-student-loan-portfolio-2e077)

In [2]:
portfolio_df = pd.read_excel('https://data.ed.gov/dataset/fb615e1a-f95f-478d-bf7b-350fdf21133e/resource/a6eb7b27-4393-410d-8db0-fec02e70203f/download/portfolio-by-age.xls')
portfolio_df

,Federal Student Loan Portfolio by Borrower Age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Includes outstanding principal and interest ba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data Source: Enterprise Data Warehouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,24 and Younger,NaN,25 to 34,NaN,35 to 49,NaN,50 to 61,NaN,62 and Older,NaN,Not Reported,NaN
4,Federal Fiscal Year,NaN,Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions)
5,2017,Q2,134.3,8.6,477.4,15.3,484.7,13.5,191.9,5.6,51.9,1.7,0.3,0.1
6,2017,Q3,126.5,8.2,477.8,15.2,490.2,13.5,194.1,5.6,53.2,1.7,0.2,0.1
7,2017,Q4,130.3,8.7,484,15.3,502.2,13.7,199.8,5.7,55.4,1.7,0.3,0.1
8,2018,Q1,124.4,8.6,483.8,15.3,511.3,13.8,204,5.7,57.9,1.8,0.2,0.1
9,2018,Q2,129.1,8.4,488.6,15.2,522.4,13.8,210.3,5.8,60.5,1.8,0.2,0.1
10,2018,Q3,121.6,8,489,15.1,529.6,13.8,213.6,5.8,62.5,1.8,0.2,0.1
11,2018,Q4,125.4,8.5,494.8,15.2,540.3,14,219.4,5.8,65.2,1.9,0.2,0.1
12,2019,Q1,120.1,8.4,494.2,15.2,548.4,14.1,224.1,5.9,67.8,1.9,0.2,0.1
13,2019,Q2,124.6,8.1,497.6,15.1,557.6,14.1,230.4,5.9,70.4,2,0.2,0.1
14,2019,Q3,117.3,7.8,497,15,564,14,234.1,5.9,72.9,2,0.2,0.1
15,2019,Q4,121.2,8.2,501.5,15,575.5,14.1,241.2,6,75.9,2.1,0.2,0.1
16,2020,Q1,116.1,8.1,498.1,14.9,581.2,14.1,245.5,6,78.5,2.1,0.3,0.1
17,2020,Q2,120.2,7.9,500.1,14.8,589.8,14.1,252.6,6,81.4,2.2,0.3,0.1
18,2020,Q3,112.8,7.5,498,14.8,594.5,14.1,256.1,6.1,83.8,2.2,0.3,0.1
19,2020,Q4,115.5,7.8,500.5,14.8,601.7,14.2,262.2,6.2,86.8,2.3,0.3,0.1
20,2021,Q1,109,7.7,496.3,14.8,604.9,14.3,266.5,6.2,89.5,2.3,0.3,0.1
21,2021,Q2,113.7,7.5,500.6,14.9,613,14.3,273.7,6.3,92.7,2.4,0.3,0.1
22,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Due to rounding and timing differences, the to...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Change column name**

In [3]:
# Make all the null values No for workability
portfolio_df = portfolio_df.fillna("No")

In [4]:
# Assign the values on index 4 as columns of the data frame
portfolio_df.columns = pd.Series(portfolio_df.iloc[4].values).str.replace("No","School Quarter (Q1-Q4)")

In [34]:
# Engineer a new set of column full column names
cols_vakues = portfolio_df.iloc[3].values
col_index = portfolio_df.iloc[3].index
running_col = "No"
new_col = []

for k,v in enumerate(cols_vakues):
    if v != "No":
        running_col = v
        new_col.append(running_col + " - " + col_index[k])
    if v == "No" and  running_col != "No":
        new_col.append(running_col + " - " + col_index[k])
        running_col = v
    elif v == "No" and  running_col == "No":
        new_col.append(col_index[k])
    
portfolio_df.columns = new_col

In [35]:
portfolio_df

,Federal Fiscal Year,School Quarter (Q1-Q4),24 and Younger - Dollars Outstanding (in billions),24 and Younger - Borrowers (in millions),25 to 34 - Dollars Outstanding (in billions),25 to 34 - Borrowers (in millions),35 to 49 - Dollars Outstanding (in billions),35 to 49 - Borrowers (in millions),50 to 61 - Dollars Outstanding (in billions),50 to 61 - Borrowers (in millions),62 and Older - Dollars Outstanding (in billions),62 and Older - Borrowers (in millions),Not Reported - Dollars Outstanding (in billions),Not Reported - Borrowers (in millions)
0,Includes outstanding principal and interest ba...,No,No,No,No,No,No,No,No,No,No,No,No,No
1,Data Source: Enterprise Data Warehouse,No,No,No,No,No,No,No,No,No,No,No,No,No
2,No,No,No,No,No,No,No,No,No,No,No,No,No,No
3,No,No,24 and Younger,No,25 to 34,No,35 to 49,No,50 to 61,No,62 and Older,No,Not Reported,No
4,Federal Fiscal Year,No,Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions)
5,2017,Q2,134.3,8.6,477.4,15.3,484.7,13.5,191.9,5.6,51.9,1.7,0.3,0.1
6,2017,Q3,126.5,8.2,477.8,15.2,490.2,13.5,194.1,5.6,53.2,1.7,0.2,0.1
7,2017,Q4,130.3,8.7,484,15.3,502.2,13.7,199.8,5.7,55.4,1.7,0.3,0.1
8,2018,Q1,124.4,8.6,483.8,15.3,511.3,13.8,204,5.7,57.9,1.8,0.2,0.1
9,2018,Q2,129.1,8.4,488.6,15.2,522.4,13.8,210.3,5.8,60.5,1.8,0.2,0.1
10,2018,Q3,121.6,8,489,15.1,529.6,13.8,213.6,5.8,62.5,1.8,0.2,0.1
11,2018,Q4,125.4,8.5,494.8,15.2,540.3,14,219.4,5.8,65.2,1.9,0.2,0.1
12,2019,Q1,120.1,8.4,494.2,15.2,548.4,14.1,224.1,5.9,67.8,1.9,0.2,0.1
13,2019,Q2,124.6,8.1,497.6,15.1,557.6,14.1,230.4,5.9,70.4,2,0.2,0.1
14,2019,Q3,117.3,7.8,497,15,564,14,234.1,5.9,72.9,2,0.2,0.1
15,2019,Q4,121.2,8.2,501.5,15,575.5,14.1,241.2,6,75.9,2.1,0.2,0.1
16,2020,Q1,116.1,8.1,498.1,14.9,581.2,14.1,245.5,6,78.5,2.1,0.3,0.1
17,2020,Q2,120.2,7.9,500.1,14.8,589.8,14.1,252.6,6,81.4,2.2,0.3,0.1
18,2020,Q3,112.8,7.5,498,14.8,594.5,14.1,256.1,6.1,83.8,2.2,0.3,0.1
19,2020,Q4,115.5,7.8,500.5,14.8,601.7,14.2,262.2,6.2,86.8,2.3,0.3,0.1
20,2021,Q1,109,7.7,496.3,14.8,604.9,14.3,266.5,6.2,89.5,2.3,0.3,0.1
21,2021,Q2,113.7,7.5,500.6,14.9,613,14.3,273.7,6.3,92.7,2.4,0.3,0.1
22,Notes:,No,No,No,No,No,No,No,No,No,No,No,No,No
23,"Due to rounding and timing differences, the to...",No,No,No,No,No,No,No,No,No,No,No,No,No

**Remove noizy rows**

In [36]:
# Select only rows from 5 to 45
portfolio_df = portfolio_df.iloc[5:23].reset_index(drop=True)

In [38]:
portfolio_df.head()

,Federal Fiscal Year,School Quarter (Q1-Q4),24 and Younger - Dollars Outstanding (in billions),24 and Younger - Borrowers (in millions),25 to 34 - Dollars Outstanding (in billions),25 to 34 - Borrowers (in millions),35 to 49 - Dollars Outstanding (in billions),35 to 49 - Borrowers (in millions),50 to 61 - Dollars Outstanding (in billions),50 to 61 - Borrowers (in millions),62 and Older - Dollars Outstanding (in billions),62 and Older - Borrowers (in millions),Not Reported - Dollars Outstanding (in billions),Not Reported - Borrowers (in millions)
0,2017,Q2,134.3,8.6,477.4,15.3,484.7,13.5,191.9,5.6,51.9,1.7,0.3,0.1
1,2017,Q3,126.5,8.2,477.8,15.2,490.2,13.5,194.1,5.6,53.2,1.7,0.2,0.1
2,2017,Q4,130.3,8.7,484,15.3,502.2,13.7,199.8,5.7,55.4,1.7,0.3,0.1
3,2018,Q1,124.4,8.6,483.8,15.3,511.3,13.8,204,5.7,57.9,1.8,0.2,0.1
4,2018,Q2,129.1,8.4,488.6,15.2,522.4,13.8,210.3,5.8,60.5,1.8,0.2,0.1

In [39]:
# Write the final cleaned data to csv
portfolio_df.to_csv("data/federal_student_aid_portfolio_by_age.csv", mode="w")