In [1]:
# !pip install pandas xlrd
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Get data

Data from [data.gov](https://catalog.data.gov/dataset/federal-student-loan-portfolio-2e077)

In [2]:
portfolio_df = pd.read_excel('https://data.ed.gov/dataset/fb615e1a-f95f-478d-bf7b-350fdf21133e/resource/65239fd0-7d1d-4685-a497-2b4137f59213/download/portfolio-by-debt-size.xls')
portfolio_df

,Federal Student Loan Portfolio by Borrower Debt Size,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Includes outstanding principal and interest ba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data Source: Enterprise Data Warehouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Less than 5K,NaN,5K to 10K,NaN,10K to 20K,NaN,20K to 40K,NaN,40K to 60K,NaN,60K to 80K,NaN,80K-100K,NaN,100K to 200K,NaN,200K+,NaN
4,Federal Fiscal Year,NaN,Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions)
5,2017,Q2,21.2,8.2,57.3,7.9,138,9.6,268,9.4,192.6,3.9,157.1,2.3,93.9,1.1,249.1,1.8,163.2,0.6
6,2017,Q3,20.8,8,56.7,7.8,136.5,9.5,265,9.3,191.9,3.9,157.6,2.3,95.3,1.1,251.1,1.8,167.2,0.6
7,2017,Q4,22.4,8.6,56.9,7.7,135.8,9.4,268.3,9.4,195.1,4,160.3,2.3,98.2,1.1,258.9,1.9,176,0.6
8,2018,Q1,23.1,8.8,56.5,7.7,135.3,9.4,266.5,9.4,195.2,4,161.2,2.3,100.1,1.1,261.7,1.9,182,0.6
9,2018,Q2,20.7,8,56.5,7.8,137.4,9.5,269.4,9.5,197.6,4,164.9,2.4,103.4,1.2,269.5,2,191.6,0.7
10,2018,Q3,20.4,7.9,56,7.7,136,9.4,266.4,9.4,196.9,4,165.3,2.4,105.2,1.2,272.7,2,197.6,0.7
11,2018,Q4,22.1,8.5,56.3,7.6,135.1,9.3,269.8,9.5,199.8,4.1,167.5,2.4,108.2,1.2,280.4,2,206.4,0.7
12,2019,Q1,22.6,8.7,55.9,7.6,134.6,9.3,268.1,9.4,199.7,4.1,168.1,2.4,110.2,1.2,283.1,2.1,212.7,0.7
13,2019,Q2,20.2,7.9,55.7,7.7,136.2,9.4,270,9.5,201.4,4.1,171.2,2.5,113.5,1.3,290.4,2.1,222.3,0.8
14,2019,Q3,19.9,7.7,55,7.6,134.6,9.3,266.7,9.4,200.3,4.1,171.2,2.5,115.1,1.3,293.5,2.1,229.3,0.8
15,2019,Q4,21.5,8.3,55.1,7.5,133.4,9.2,270,9.5,202.9,4.1,173.2,2.5,117.9,1.3,301.7,2.2,239.8,0.8
16,2020,Q1,21.8,8.4,54.6,7.4,132.4,9.1,267.7,9.4,201.9,4.1,173.1,2.5,119.3,1.3,303.1,2.2,245.8,0.8
17,2020,Q2,19.6,7.7,54.3,7.5,134.3,9.3,269.1,9.4,203.2,4.1,175.7,2.5,121.9,1.4,310.3,2.3,256,0.9
18,2020,Q3,19.4,7.4,54.2,7.5,134.1,9.3,267.7,9.4,203.1,4.1,175.6,2.5,122.3,1.4,311.5,2.3,257.6,0.9
19,2020,Q4,20.7,7.9,54.6,7.4,133.1,9.2,272.3,9.6,205.8,4.2,177,2.6,123.2,1.4,317.2,2.3,263.1,0.9
20,2021,Q1,21.2,8,54.4,7.4,132.6,9.1,271.4,9.5,205.7,4.2,176.9,2.6,123.1,1.4,317.2,2.3,263.9,0.9
21,2021,Q2,19.4,7.3,54.4,7.5,136.4,9.4,274.2,9.6,208.7,4.3,179.9,2.6,125.3,1.4,324.2,2.4,271.3,0.9
22,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Due to rounding and timing differences, the to...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Change column name**

In [3]:
# Make all the null values No for workability
portfolio_df = portfolio_df.fillna("No")

In [4]:
# Assign the values on index 4 as columns of the data frame
portfolio_df.columns = pd.Series(portfolio_df.iloc[4].values).str.replace("No","School Quarter (Q1-Q4)")

In [6]:
# Engineer a new set of column full column names
cols_vakues = portfolio_df.iloc[3].values
col_index = portfolio_df.iloc[3].index
running_col = "No"
new_col = []

for k,v in enumerate(cols_vakues):
    if v != "No":
        running_col = v
        new_col.append(running_col + " - " + col_index[k])
    if v == "No" and  running_col != "No":
        new_col.append(running_col + " - " + col_index[k])
        running_col = v
    elif v == "No" and  running_col == "No":
        new_col.append(col_index[k])
    
portfolio_df.columns = new_col

In [7]:
portfolio_df

,Federal Fiscal Year,School Quarter (Q1-Q4),Less than 5K - Dollars Outstanding (in billions),Less than 5K - Borrowers (in millions),5K to 10K - Dollars Outstanding (in billions),5K to 10K - Borrowers (in millions),10K to 20K - Dollars Outstanding (in billions),10K to 20K - Borrowers (in millions),20K to 40K - Dollars Outstanding (in billions),20K to 40K - Borrowers (in millions),40K to 60K - Dollars Outstanding (in billions),40K to 60K - Borrowers (in millions),60K to 80K - Dollars Outstanding (in billions),60K to 80K - Borrowers (in millions),80K-100K - Dollars Outstanding (in billions),80K-100K - Borrowers (in millions),100K to 200K - Dollars Outstanding (in billions),100K to 200K - Borrowers (in millions),200K+ - Dollars Outstanding (in billions),200K+ - Borrowers (in millions)
0,Includes outstanding principal and interest ba...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No
1,Data Source: Enterprise Data Warehouse,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No
2,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No
3,No,No,Less than 5K,No,5K to 10K,No,10K to 20K,No,20K to 40K,No,40K to 60K,No,60K to 80K,No,80K-100K,No,100K to 200K,No,200K+,No
4,Federal Fiscal Year,No,Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions),Dollars Outstanding (in billions),Borrowers (in millions)
5,2017,Q2,21.2,8.2,57.3,7.9,138,9.6,268,9.4,192.6,3.9,157.1,2.3,93.9,1.1,249.1,1.8,163.2,0.6
6,2017,Q3,20.8,8,56.7,7.8,136.5,9.5,265,9.3,191.9,3.9,157.6,2.3,95.3,1.1,251.1,1.8,167.2,0.6
7,2017,Q4,22.4,8.6,56.9,7.7,135.8,9.4,268.3,9.4,195.1,4,160.3,2.3,98.2,1.1,258.9,1.9,176,0.6
8,2018,Q1,23.1,8.8,56.5,7.7,135.3,9.4,266.5,9.4,195.2,4,161.2,2.3,100.1,1.1,261.7,1.9,182,0.6
9,2018,Q2,20.7,8,56.5,7.8,137.4,9.5,269.4,9.5,197.6,4,164.9,2.4,103.4,1.2,269.5,2,191.6,0.7
10,2018,Q3,20.4,7.9,56,7.7,136,9.4,266.4,9.4,196.9,4,165.3,2.4,105.2,1.2,272.7,2,197.6,0.7
11,2018,Q4,22.1,8.5,56.3,7.6,135.1,9.3,269.8,9.5,199.8,4.1,167.5,2.4,108.2,1.2,280.4,2,206.4,0.7
12,2019,Q1,22.6,8.7,55.9,7.6,134.6,9.3,268.1,9.4,199.7,4.1,168.1,2.4,110.2,1.2,283.1,2.1,212.7,0.7
13,2019,Q2,20.2,7.9,55.7,7.7,136.2,9.4,270,9.5,201.4,4.1,171.2,2.5,113.5,1.3,290.4,2.1,222.3,0.8
14,2019,Q3,19.9,7.7,55,7.6,134.6,9.3,266.7,9.4,200.3,4.1,171.2,2.5,115.1,1.3,293.5,2.1,229.3,0.8
15,2019,Q4,21.5,8.3,55.1,7.5,133.4,9.2,270,9.5,202.9,4.1,173.2,2.5,117.9,1.3,301.7,2.2,239.8,0.8
16,2020,Q1,21.8,8.4,54.6,7.4,132.4,9.1,267.7,9.4,201.9,4.1,173.1,2.5,119.3,1.3,303.1,2.2,245.8,0.8
17,2020,Q2,19.6,7.7,54.3,7.5,134.3,9.3,269.1,9.4,203.2,4.1,175.7,2.5,121.9,1.4,310.3,2.3,256,0.9
18,2020,Q3,19.4,7.4,54.2,7.5,134.1,9.3,267.7,9.4,203.1,4.1,175.6,2.5,122.3,1.4,311.5,2.3,257.6,0.9
19,2020,Q4,20.7,7.9,54.6,7.4,133.1,9.2,272.3,9.6,205.8,4.2,177,2.6,123.2,1.4,317.2,2.3,263.1,0.9
20,2021,Q1,21.2,8,54.4,7.4,132.6,9.1,271.4,9.5,205.7,4.2,176.9,2.6,123.1,1.4,317.2,2.3,263.9,0.9
21,2021,Q2,19.4,7.3,54.4,7.5,136.4,9.4,274.2,9.6,208.7,4.3,179.9,2.6,125.3,1.4,324.2,2.4,271.3,0.9
22,Notes:,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No
23,"Due to rounding and timing differences, the to...",No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No

**Remove noizy rows**

In [8]:
# Select only rows from 5 to 45
portfolio_df = portfolio_df.iloc[5:23].reset_index(drop=True)

In [9]:
portfolio_df.head()

,Federal Fiscal Year,School Quarter (Q1-Q4),Less than 5K - Dollars Outstanding (in billions),Less than 5K - Borrowers (in millions),5K to 10K - Dollars Outstanding (in billions),5K to 10K - Borrowers (in millions),10K to 20K - Dollars Outstanding (in billions),10K to 20K - Borrowers (in millions),20K to 40K - Dollars Outstanding (in billions),20K to 40K - Borrowers (in millions),40K to 60K - Dollars Outstanding (in billions),40K to 60K - Borrowers (in millions),60K to 80K - Dollars Outstanding (in billions),60K to 80K - Borrowers (in millions),80K-100K - Dollars Outstanding (in billions),80K-100K - Borrowers (in millions),100K to 200K - Dollars Outstanding (in billions),100K to 200K - Borrowers (in millions),200K+ - Dollars Outstanding (in billions),200K+ - Borrowers (in millions)
0,2017,Q2,21.2,8.2,57.3,7.9,138,9.6,268,9.4,192.6,3.9,157.1,2.3,93.9,1.1,249.1,1.8,163.2,0.6
1,2017,Q3,20.8,8,56.7,7.8,136.5,9.5,265,9.3,191.9,3.9,157.6,2.3,95.3,1.1,251.1,1.8,167.2,0.6
2,2017,Q4,22.4,8.6,56.9,7.7,135.8,9.4,268.3,9.4,195.1,4,160.3,2.3,98.2,1.1,258.9,1.9,176,0.6
3,2018,Q1,23.1,8.8,56.5,7.7,135.3,9.4,266.5,9.4,195.2,4,161.2,2.3,100.1,1.1,261.7,1.9,182,0.6
4,2018,Q2,20.7,8,56.5,7.8,137.4,9.5,269.4,9.5,197.6,4,164.9,2.4,103.4,1.2,269.5,2,191.6,0.7

In [10]:
# Write the final cleaned data to csv
portfolio_df.to_csv("data/federal_student_aid_portfolio_by_debt_size.csv", mode="w")